@startuml Manage User (GET)

header Coworking Space Reservation System Sequence Diagram
footer Group Yossawat & Supanut
title "Manage User (GET)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:auth" as routerAuth
participant "<<controllers>>\n:auth" as controllersAuth
participant "<<model>>\n:User" as modelUser
database "<<MySQL>>\n:coworkingspaces" as CoworkingSpacesDatabase

client->server ++:req.get('/me')
server->routerAuth ++:app.use('/auth',auth)
routerAuth->controllersAuth ++:getMe(req.user.id)
controllersAuth->modelUser ++:findByPk(req.user.id)
modelUser->CoworkingSpacesDatabase ++:UserSchema
CoworkingSpacesDatabase-->modelUser --:user
modelUser-->controllersAuth --:user
controllersAuth-->client --:res.status(200).json({ success: true, data: user.dataValues })
