@startuml Manage CoworkingSpace (POST)

header Coworking Space Reservation System Sequence Diagram
footer Group Yossawat & Supanut
title "Manage CoworkingSpace (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:coworkingspaces" as routerCoworkingSpaces
participant "<<middleware>>\n:auth" as middleware
participant "<<controllers>>\n:coworkingspaces" as controllersCoworkingSpaces
participant "<<model>>\n:CoworkingSpace" as modelCoworkingSpace
database "<<MySQL>>\n:coworkingspaces" as CoworkingSpacesDatabase

client->server ++:req.post('/coworkingspaces')
server->routerCoworkingSpaces ++:app.use('/coworkingspaces',coworkingspaces)
routerCoworkingSpaces -> middleware ++:protect()\nauthorize('admin')
alt Already logged in and correct role
    middleware --> routerCoworkingSpaces : next()
    routerCoworkingSpaces -> controllersCoworkingSpaces ++: createCoworkingSpace()
else Not logged in yet
    middleware --> client : res.status(401).json({ sucess: false, message: 'Not authorize to access this route' })
else Wrong role
    middleware --> client --: res.status(403).json({ sucess: false, message: `User role ${req.user.role} is not authorized to access this route` })
end
controllersCoworkingSpaces-> modelCoworkingSpace ++:create(req.body)
modelCoworkingSpace -> CoworkingSpacesDatabase ++: CoworkingSpaceSchema
CoworkingSpacesDatabase --> modelCoworkingSpace --: coworkingspace
controllersCoworkingSpaces <-- modelCoworkingSpace --:coworkingspace
controllersCoworkingSpaces --> client --: res.status(201).json({ success: true, data: coworkingspace.dataValues })

@enduml
